// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdjmHp45TcSMZeh6NSQllWmKksIWeggXg',
    appId: '1:822707180641:web:56dc999b2f1953791c8620',
    messagingSenderId: '822707180641',
    projectId: 'photoris-6b7cc',
    authDomain: 'photoris-6b7cc.firebaseapp.com',
    storageBucket: 'photoris-6b7cc.appspot.com',
    measurementId: 'G-ETXDD7F6R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZPuYkX6QyWPpf6VcyEjyCiz6saIVJN4c',
    appId: '1:822707180641:android:0be0832cab36855b1c8620',
    messagingSenderId: '822707180641',
    projectId: 'photoris-6b7cc',
    storageBucket: 'photoris-6b7cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkzIw3uUSKgn2EQJxLHqABrlpyRA8VYgk',
    appId: '1:822707180641:ios:3caaeb07cee9884c1c8620',
    messagingSenderId: '822707180641',
    projectId: 'photoris-6b7cc',
    storageBucket: 'photoris-6b7cc.appspot.com',
    iosClientId: '822707180641-ji9bi5dqtshjbn10hn0t0cbeg7bh9eni.apps.googleusercontent.com',
    iosBundleId: 'com.photoris.app',
  );
}
